global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308', 'jmx-exporter-broker1:5556', 'jmx-exporter-broker2:5557', 'jmx-exporter-broker3:5558']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'jmx-brokers'
    static_configs:
      - targets: ['jmx-exporter-broker1:5556', 'jmx-exporter-broker2:5557', 'jmx-exporter-broker3:5558']

  - job_name: 'flink'
    static_configs:
      - targets: ['flink-jobmanager:9249', 'flink-taskmanager:9249']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

rule_files:
  - "/etc/prometheus/rules/cdr_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
