global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'at.critical.bigdata@gmail.com'
  smtp_auth_username: 'at.critical.bigdata@gmail.com'
  smtp_auth_password: 'fepnrkcmzsauhlgy'
  smtp_require_tls: true
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'critical-team'
  routes:
    - match:
        severity: critical
      receiver: 'critical-team'
    - match:
        severity: warning
      receiver: 'bigdata-team'

receivers:
  - name: 'bigdata-team'
    email_configs:
      - to: 'at.critical.bigdata@gmail.com'

  - name: 'critical-team'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alerts'
        send_resolved: true

inhibit_rules: []
